// filepath: c:\Users\kisho\Documents\Personal\My AI\frontend\src\app\layout.js
import "./globals.css";

export const metadata = {
  title: "XendrixAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="/fonts/geist.css"
        />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}